### ISSUE TITLE
Incompatibility with LiteLoader

### ISSUE THREAD

**Issue by Tsoccerguy3** [DimensionalDevelopment/VanillaFix#27]
VanillaFix-1.0.4-35 , error on multiplayer server login

Internal Exception : java.lang.NoclassDefFoundError: net/minecraft/network/NetHandlerPlayServer

Windows 10 x64

**Comment by Runemoro** [comment]
Please upload a full log. That single line is useless for finding the cause of this issue.

**Comment by ZombieHDGaming** [comment]
If I had to bet, you have Liteloader installed. If you do, remove it for the time being as we need to advise Liteloader to possibly make some changes.

**Comment by Tsoccerguy3** [comment]
There is no crash or crash log . I checked for the error in the Forge log . Your right it's a problem with mixins and liteloader  . To duplicate this error just put the liteloader1.12.2.jar into , .minecraft / mods / 1.12.2 /

**Comment by Robijnvogel** [comment]
@Tsoccerguy3 that's not even how you should install Liteloader. It comes as a runnable .jar file.

**Comment by poutrosgit** [comment]
@Robijnvogel Liteloader can very well be loaded by forge. Otherwise it wouldn't even crash because forge would ignore it.

**Comment by grydian** [comment]
Actually placing liteloader into the mods folder is exactly how you should install liteloader for the twitch launcher.  I am also getting this crash.  https://pastebin.com/GnMctUY6

**Comment by Tsoccerguy3** [comment]
Has anyone got hold of Mumfrey and ask if he will add the appropriate hooks to Liteloader ?

**Comment by Tsoccerguy3** [comment]
Any luck getting this bug fixed ?

**Comment by Runemoro** [comment]
It would be better if LiteLoader fixed this.

LiteLoader should use the same injection point as Sponge (queuedEndExit), since that one works properly with VanillaFix, and it is much less likely to break than something meaningless like "the fourth usage of `posY`" (http://develop.liteloader.com/liteloader/LiteLoader/blob/master/src/main/java/com/mumfrey/liteloader/common/mixin/MixinNetHandlerPlayServer.java#L114).

**Comment by grydian** [comment]
I don't have a gitlab account.  Can some please create the issue?

**Comment by Tsoccerguy3** [comment]
I sent Mumfrey a message

**Comment by grydian** [comment]
Is there any chance he hasn't seen it because I have seen zero updates on this...

**Comment by ZombieHDGaming** [comment]
@grydian This was fixed in 1.0.8.......

**Comment by poutrosgit** [comment]
By removing the movement stuff, right?

**Comment by ZombieHDGaming** [comment]
Yes. Mumfrey will still need to fix this issue in the future, but for the time being, Liteloader is compatible again with LiteLoader. I might have to make an issue on his tracker to speed things up on fixing the issue for the future.

**Comment by Mumfrey** [comment]
Someone pinged me about this on MCF, I'll take a look into it.

**Comment by RainOfPain125** [comment]
https://pastebin.com/wjL76dNN

Incompatibility with LL still exists, almost 3 years later.

damn.

**Comment by BoogieMonster1O1** [comment]
> https://pastebin.com/wjL76dNN
> 
> Incompatibility with LL still exists, almost 3 years later.
> 
> damn.

check the pinned issues. there's two ways to fix it.
and make sure you're using the latest vanillafix (1.0.10-150)

**Comment by RainOfPain125** [comment]
> > https://pastebin.com/wjL76dNN
> > Incompatibility with LL still exists, almost 3 years later.
> > damn.
> 
> check the pinned issues. there's two ways to fix it.
> and make sure you're using the latest vanillafix (1.0.10-150)

Alright, just tried renaming VanillaFix to _VanillaFix (which makes it first mod alphabetically in my mods) and put 0.7-0.8 compatibility, neither worked on their own or together.

**Comment by RainOfPain125** [comment]
The errors seem different (I think). Here is the new pastebin with mostly just the error parts.

https://pastebin.com/5xYULRR9

**Comment by RainOfPain125** [comment]
hoping this gets solved, quickly.
